name: Upload Chrome extension
on: [workflow_dispatch]
jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: wdzeng/chrome-extension@v1
        with:
          extension-id: your-extension-id
          zip-path: build/extension.zip
          tester-only: false
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}