name: Upload Edge Add-on

on: [workflow_dispatch]

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: wdzeng/edge-addon@v1
        with:
          product-id: fpjkbmpnfckpnaiijocjdfcjddnkjhnb
          zip-path: build/extension.zip
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.EDGE_REFRESH_TOKEN_URL }}
