name: Upload Firefox Add-on

on: [workflow_dispatch]

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: wdzeng/firefox-addon@v1
        with:
          addon-guid: your-addon's-guid
          xpi-path:  build/extension.zip
          self-hosted: false
          jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
          jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
